#CFT liste
# 1-16: rainfed
# 1: temperate cereals (rainfed)
# 2: rice (rainfed)
# 3: maize (rainfed)
# 4: tropical cereals (rainfed)
# 5: pulses (rainfed)
# 6: temperate roots (rainfed)
# 7: tropical roots (rainfed)
# 8: oil crops sunflower (rainfed)
# 9: oil crops soybean (rainfed)
# 10: oil crops groundnut (rainfed)
# 11: oil crops rapeseed (rainfed)
# 12: sugar cane (rainfed)
# 13: other crops (rainfed)
# 14: pasture/managed grass (C3/C4 mixed) (rainfed)
# 15: bio-energy grass (rainfed)
# 16: bio-energy tree (rainfed)

# 17-32: surface
# 17: temperate cereals (surface)
# 18: rice (surface)
# 19: maize (surface)
# 20: tropical cereals (surface)
# 21: pulses (surface)
# 22: temperate roots (surface)
# 23: tropical roots (surface)
# 24: oil crops sunflower (surface)
# 25: oil crops soybean (surface)
# 26: oil crops groundnut (surface)
# 27: oil crops rapeseed (surface)
# 28: sugar cane (surface)
# 29: other crops (surface)
# 30: pasture/managed grass (C3/C4 mixed) (surface)
# 31: bio-energy grass (surface)
# 32: bio-energy tree (surface)

# 33-48: sprinkler
# 33: temperate cereals (sprinkler)
# 34: rice (sprinkler)
# 35: maize (sprinkler)
# 36: tropical cereals (sprinkler)
# 37: pulses (sprinkler)
# 38: temperate roots (sprinkler)
# 39: tropical roots (sprinkler)
# 40: oil crops sunflower (sprinkler)
# 41: oil crops soybean (sprinkler)
# 42: oil crops groundnut (sprinkler)
# 43: oil crops rapeseed (sprinkler)
# 44: sugar cane (sprinkler)
# 45: other crops (sprinkler)
# 46: pasture/managed grass (C3/C4 mixed) (sprinkler)
# 47: bio-energy grass (sprinkler)
# 48: bio-energy tree (sprinkler)

# 49-64: drip
# 49: temperate cereals (drip)
# 50: rice (drip)
# 51: maize (drip)
# 52: tropical cereals (drip)
# 53: pulses (drip)
# 54: temperate roots (drip)
# 55: tropical roots (drip)
# 56: oil crops sunflower (drip)
# 57: oil crops soybean (drip)
# 58: oil crops groundnut (drip)
# 59: oil crops rapeseed (drip)
# 60: sugar cane (drip)
# 61: other crops (drip)
# 62: pasture/managed grass (C3/C4 mixed) (drip)
# 63: bio-energy grass (drip)
# 64: bio-energy tree (drip)